<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Define properties -->
  <xacro:property name="stator_size" value="0.102" />
  <xacro:property name="rotor_radius" value="0.025" />
  <xacro:property name="rotor_length" value="0.01" />
  <xacro:property name="angle_length" value="0.025" />
  <xacro:property name="angle_width" value="0.002" />
  <xacro:property name="angle_height" value="0.002" />

  <!-- Macro definition -->
  <xacro:macro name="joint_model" params="prefix">
    <!-- Base link -->
    <link name="${prefix}base_link">
      <visual>
        <geometry/>
      </visual>
    </link>

    <!-- Stator link -->
    <link name="${prefix}stator_link">
      <visual>
        <geometry>
          <box size="${stator_size} ${stator_size} ${stator_size}"/>
        </geometry>
        <material name="black"/>
      </visual>
    </link>

    <!-- Rotor link -->
    <link name="${prefix}rotor_link">
      <visual>
        <geometry>
          <cylinder radius="${rotor_radius}" length="${rotor_length}"/>
        </geometry>
        <material name="red"/>
      </visual>
    </link>

    <!-- Angle link -->
    <link name="${prefix}angle_link">
      <visual>
        <geometry>
          <box size="${angle_length} ${angle_width} ${angle_height}"/>
        </geometry>
        <material name="white"/>
      </visual>
    </link>

    <!-- Joints -->
    <joint name="${prefix}stator_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}stator_link"/>
      <origin xyz="0 0 ${stator_size/2}"/>
    </joint>

    <joint name="${prefix}angle" type="revolute">
      <parent link="${prefix}stator_link"/>
      <child link="${prefix}rotor_link"/>
      <origin xyz="0 0 ${stator_size/2}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-3.14" upper="3.14" effort="0" velocity="0"/>
    </joint>

    <joint name="${prefix}indicator" type="fixed">
      <parent link="${prefix}rotor_link"/>
      <child link="${prefix}angle_link"/>
      <origin xyz="${rotor_radius} 0 0"/>
    </joint>
  </xacro:macro>
</robot>